# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch
# Create random tensor
random_tensor = torch.rand((7,7))
random_tensor

tensor([[0.9853, 0.0344, 0.9363, 0.9973, 0.8308, 0.1398, 0.5297],
        [0.0282, 0.2724, 0.7787, 0.6215, 0.6640, 0.2085, 0.8321],
        [0.1734, 0.0754, 0.5911, 0.7054, 0.0278, 0.0815, 0.1147],
        [0.5172, 0.9541, 0.8123, 0.4559, 0.8021, 0.1066, 0.9681],
        [0.1486, 0.0038, 0.8079, 0.0613, 0.0296, 0.3772, 0.1560],
        [0.6036, 0.2621, 0.7554, 0.2982, 0.8511, 0.7688, 0.4550],
        [0.0133, 0.9552, 0.7331, 0.2240, 0.6559, 0.1935, 0.7258]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor

# Perform matrix multiplication 
second_tensor = torch.rand((1, 7))
random_tensor @ second_tensor.T

tensor([[1.9262],
        [1.3881],
        [0.7050],
        [1.9584],
        [0.7177],
        [1.6309],
        [1.3261]])

In [4]:
torch.mm(random_tensor, second_tensor.T)

tensor([[1.9262],
        [1.3881],
        [0.7050],
        [1.9584],
        [0.7177],
        [1.6309],
        [1.3261]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor = torch.rand((7,7))
second_tensor = torch.rand((1,7))


# Matrix multiply tensors
torch.mm(random_tensor, second_tensor.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Create two random tensors on GPU
tensor1 = torch.rand((2,3), device=device)
tensor2 = torch.rand((2,3), device=device)
# tensor1 = torch.rand((2,3)).to(device)
# tensor2 = torch.rand((2,3)).to(device)

tensor1, tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
M = tensor1 @ tensor2.T
M

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
print(M.max())
# Find min
print(M.min())

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [13]:
# Find arg max
print(M.argmax())

# Find arg min
print(M.argmin())

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [14]:
# Set seed
torch.manual_seed(7)

# Create random tensor
new_tensor = torch.rand((1, 1, 1, 10))

# Remove single dimensions
squeezed_tensor = new_tensor.squeeze()

# Print out tensors and their shapes
print(new_tensor, new_tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
