In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.5794, 0.4259],
        [0.2329, 0.0983]])


In [6]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zero_tensor)

tensor([[0.0261, 0.4998, 0.0285],
        [0.5251, 0.6274, 0.2717]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3, 4)

tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [ ]:
tensor = torch.ones(4, 4)

print(tensor[0])
print(tensor[:,0])
print(tensor[..., -1]) # ... (ellipsis) in indexing means “select all dimensions up to this point.”

tensor[:, 1] = 0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
test = torch.rand((4,2,3))
print(test)

print(test[..., -1])

tensor([[[0.2132, 0.1580, 0.2446],
         [0.1123, 0.8204, 0.6113]],

        [[0.0601, 0.2362, 0.2217],
         [0.5887, 0.2242, 0.5638]],

        [[0.8060, 0.3041, 0.2198],
         [0.3071, 0.8167, 0.9309]],

        [[0.7892, 0.6379, 0.4461],
         [0.3991, 0.9747, 0.9869]]])
tensor([[0.2446, 0.6113],
        [0.2217, 0.5638],
        [0.2198, 0.9309],
        [0.4461, 0.9869]])


In [13]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim= 1)
t1, t1.shape

(tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
         [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]),
 torch.Size([4, 12]))

In [24]:
t3 = torch.cat([tensor, tensor, tensor], dim = 0)
t3, t3.shape

(tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]),
 torch.Size([12, 4]))

In [21]:
t2 = torch.stack([tensor, tensor, tensor], dim = 0)
t2, t2.shape

(tensor([[[1., 0., 1., 1.],
          [1., 0., 1., 1.],
          [1., 0., 1., 1.],
          [1., 0., 1., 1.]],
 
         [[1., 0., 1., 1.],
          [1., 0., 1., 1.],
          [1., 0., 1., 1.],
          [1., 0., 1., 1.]],
 
         [[1., 0., 1., 1.],
          [1., 0., 1., 1.],
          [1., 0., 1., 1.],
          [1., 0., 1., 1.]]]),
 torch.Size([3, 4, 4]))