In [111]:
import torch
torch.__version__

'2.5.1'

#### a tensor 

In [112]:
scalar = torch.tensor(1)
scalar

tensor(1)

#### number of dimension

In [113]:
scalar.ndim

0

In [114]:
scalar.item(), type(scalar.item())

(1, int)

In [115]:
vector = torch.tensor([2, 4])
vector

tensor([2, 4])

In [116]:
vector.ndim

1

In [117]:
MATRIX = torch.tensor([[2,3], [4,5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [118]:
MATRIX.ndim

2

In [119]:
MATRIX.shape

torch.Size([2, 2])

In [120]:
test = torch.tensor([[[7, 4], [0, 1]],
                     [[1, 9,], [2, 3]],
                     [[5, 6], [8, 8]]
                     ])
test

tensor([[[7, 4],
         [0, 1]],

        [[1, 9],
         [2, 3]],

        [[5, 6],
         [8, 8]]])

In [121]:
test.shape

torch.Size([3, 2, 2])

Same color to find dimension

In [122]:
random_tensor = torch.rand((3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2933, 0.5889, 0.4117, 0.0992],
         [0.3078, 0.7786, 0.8016, 0.3649],
         [0.6286, 0.9663, 0.7687, 0.4566]]),
 torch.float32)

In [123]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor

tensor([[[0.5745, 0.9200, 0.3230],
         [0.8613, 0.0919, 0.3102],
         [0.9536, 0.6002, 0.0351],
         ...,
         [0.6501, 0.1374, 0.3852],
         [0.7029, 0.0650, 0.1280],
         [0.0728, 0.4482, 0.8423]],

        [[0.3919, 0.1191, 0.7616],
         [0.9423, 0.8760, 0.9324],
         [0.3308, 0.0646, 0.4916],
         ...,
         [0.4601, 0.4145, 0.8877],
         [0.7979, 0.1490, 0.8975],
         [0.3493, 0.3416, 0.2586]],

        [[0.9752, 0.2840, 0.2329],
         [0.7765, 0.1522, 0.3084],
         [0.0165, 0.2109, 0.1842],
         ...,
         [0.7706, 0.6538, 0.3952],
         [0.1024, 0.6485, 0.3496],
         [0.7555, 0.3809, 0.3577]],

        ...,

        [[0.8716, 0.6351, 0.7019],
         [0.3454, 0.4896, 0.8905],
         [0.9717, 0.3601, 0.9916],
         ...,
         [0.7278, 0.2134, 0.2524],
         [0.1369, 0.8770, 0.7452],
         [0.5307, 0.9066, 0.6534]],

        [[0.2118, 0.8450, 0.1104],
         [0.3851, 0.9572, 0.7999],
         [0.

In [124]:
torch.ones((3,4))


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [125]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [126]:
zero_to_ten = torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
like = torch.zeros_like(zero_to_ten)
like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
import torch

In [129]:
float_32_tensor = torch.tensor([2.0, 3., 4.], dtype = None, device=None, requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [130]:
torch.tensor([10., 11.], dtype=torch.float16)

tensor([10., 11.], dtype=torch.float16)

Three most common attributes about a tensor are:
- shape
- dtype
- device

In [131]:
some_tensor = torch.rand(3, 4)
print(some_tensor)
print("shape: ", some_tensor.shape)
print("data type: ", some_tensor.dtype)
print("device: ", some_tensor.device)

tensor([[0.3588, 0.9211, 0.8627, 0.8223],
        [0.5248, 0.5881, 0.2746, 0.3791],
        [0.2975, 0.6450, 0.0163, 0.9160]])
shape:  torch.Size([3, 4])
data type:  torch.float32
device:  cpu


In [132]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [133]:
tensor * 10

tensor([10, 20, 30])

In [134]:
#tensor doesn't change if you don't reassign it
tensor

tensor([1, 2, 3])

In [135]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [136]:
tensor += 10
tensor

tensor([1, 2, 3])

In [137]:
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [138]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [139]:
#original tensor is still unchanged
tensor 

tensor([1, 2, 3])

In [140]:
# element-wise multiplication
print(tensor, "*", tensor)
print("equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:  tensor([1, 4, 9])


In [141]:
#in python @ is the symbol for matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [142]:
torch.matmul(tensor, tensor)

tensor(14)

In [143]:
tensor @ tensor

tensor(14)

In [144]:
%%time
res = 0
for val in tensor:
    res += val**2
res


CPU times: user 852 μs, sys: 0 ns, total: 852 μs
Wall time: 538 μs


tensor(14)

In [145]:
%%time 
tensor @ tensor

CPU times: user 53 μs, sys: 8 μs, total: 61 μs
Wall time: 63.4 μs


tensor(14)

### Matrix multiplication

In [146]:
tensor_A = torch.rand((3,2))
tensor_B = torch.rand((3,2))

tensor_A, tensor_B

(tensor([[0.5888, 0.8403],
         [0.4761, 0.7140],
         [0.4644, 0.6362]]),
 tensor([[0.8892, 0.1317],
         [0.7164, 0.2706],
         [0.6560, 0.6614]]))

In [147]:
tensor_B.T

tensor([[0.8892, 0.7164, 0.6560],
        [0.1317, 0.2706, 0.6614]])

In [148]:
tensor_A @ tensor_B.T

tensor([[0.6342, 0.6491, 0.9419],
        [0.5173, 0.5342, 0.7845],
        [0.4968, 0.5049, 0.7254]])

In [149]:
torch.mm(tensor_A, tensor_B.T)

tensor([[0.6342, 0.6491, 0.9419],
        [0.5173, 0.5342, 0.7845],
        [0.4968, 0.5049, 0.7254]])

In [150]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[0.6342, 0.6491, 0.9419],
        [0.5173, 0.5342, 0.7845],
        [0.4968, 0.5049, 0.7254]])

### Test with Linear function

In [151]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, out_features= 4) # create a layer of 4 units

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}")
print(f"output: {output}\n with shape: {output.shape}")

Input shape: torch.Size([3, 2])
output: tensor([[ 1.4348, -0.0705,  0.6433,  0.2786],
        [ 1.2997, -0.1339,  0.6427,  0.2649],
        [ 1.2478, -0.1824,  0.6334,  0.2367]], grad_fn=<AddmmBackward0>)
 with shape: torch.Size([3, 4])


### Finding the min, max, mean, sum, etc (aggregation)

In [152]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [153]:
print("Minimum: {}".format(x.min()))
print("Maximum: {}".format(x.max()))
print("Mean: {}".format(x.type(torch.float32).mean())) # mean() wont work without float datatype
print("Sum: {}".format(x.sum()))


Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


#### Positional min/max
You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.
This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [154]:
tensor = torch.arange(10, 100, 10)
print("Tensor: ", tensor)

print(f"Index of the max value is: {tensor.argmax()}")
print(f"Index of the min value is: {tensor.argmin()}")


Tensor:  tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index of the max value is: 8
Index of the min value is: 0


#### Change tensor datatype
As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using `torch.Tensor.type(dtype=None)` where the dtype parameter is the datatype you'd like to use.

First we'll create a tensor and check its datatype (the default is torch.float32).

In [155]:
tensor = torch.arange(10, 100, 10)
tensor.dtype

torch.int64

In [156]:
tensor_float32 = tensor.type(torch.float32)
tensor_float32.dtype

torch.float32

### Reshaping, stacking, squeezing and unsqueezing

often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

|Method |	One-line description|
|:-----|:---:|
|torch.reshape(input, shape) |	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape(). |
|Tensor.view(shape) |	Returns a view of the original tensor in a different shape but shares the same data as the original tensor. |
|torch.stack(tensors, dim=0) |	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size. |
|torch.squeeze(input) |	Squeezes input to remove all the dimenions with value 1.|
|torch.unsqueeze(input, dim) |	Returns input with a dimension value of 1 added at dim. |
|torch.permute(input, dims) |	Returns a view of the original input with its dimensions permuted (rearranged) to dims.|

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.


In [157]:
tensor = torch.arange(1., 8)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [158]:
tensor.dtype

torch.float32

In [159]:
tensor_reshaped = tensor.reshape(1, 7)
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [160]:
tensor_C = torch.arange(1., 9)
tensor_C

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [161]:
z = tensor_C.view(2, 4)
z
# Change view (keeps same data as original but changes view)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])



Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.


In [162]:
z[:, 0] = -1
z, tensor_C

(tensor([[-1.,  2.,  3.,  4.],
         [-1.,  6.,  7.,  8.]]),
 tensor([-1.,  2.,  3.,  4., -1.,  6.,  7.,  8.]))

In [163]:
x_stacked = torch.stack([tensor for i in range(4)], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [164]:
x_stacked[:, 0] = 5
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

How about remove all single dimensions from a tensor?

To do so you can use `torch.squeeze()`

In [165]:
print(f"previous tensor: {tensor_reshaped}")
print(f"previous tensor's shape: {tensor_reshaped.shape}")

x_squeezed = tensor_reshaped.squeeze()

print(f"new tensor: {x_squeezed}")
print(f"new tensor: {x_squeezed.shape}")

previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
previous tensor's shape: torch.Size([1, 7])
new tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
new tensor: torch.Size([7])


In [166]:
x_stacked.shape

torch.Size([4, 7])

In [167]:
new_stacked_squeezed = x_stacked.squeeze()
new_stacked_squeezed.shape

torch.Size([4, 7])

In [168]:
new_stacked_squeezed #so that squeeze just remove single dimension

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [169]:
x_org = torch.rand((224, 224, 3))
x_permuted = x_org.permute(2, 0, 1)# shifts axis 0->1, 1->2, 2->0

x_org.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [170]:
x_org

tensor([[[8.6940e-01, 5.6772e-01, 7.4109e-01],
         [4.2940e-01, 8.8544e-01, 5.7390e-01],
         [2.6658e-01, 6.2745e-01, 2.6963e-01],
         ...,
         [8.8455e-01, 3.8850e-01, 3.9324e-01],
         [4.5545e-02, 4.2129e-01, 8.5366e-01],
         [5.6972e-01, 2.0877e-01, 6.5391e-01]],

        [[3.3968e-01, 9.5650e-01, 6.6023e-02],
         [3.4206e-01, 1.7213e-02, 3.0308e-01],
         [6.5762e-01, 9.8131e-01, 5.8397e-01],
         ...,
         [6.7008e-01, 6.1587e-02, 4.2213e-01],
         [4.8892e-01, 2.9742e-01, 6.8196e-01],
         [5.3223e-01, 8.5103e-01, 4.5559e-01]],

        [[1.8443e-01, 8.5328e-01, 5.6982e-01],
         [3.5680e-01, 1.7045e-01, 6.1719e-01],
         [2.3124e-02, 6.3169e-01, 7.4722e-01],
         ...,
         [5.4622e-01, 6.2962e-01, 4.5285e-01],
         [8.4301e-01, 2.0853e-01, 6.7919e-01],
         [4.9887e-01, 9.3264e-02, 3.0635e-01]],

        ...,

        [[7.5457e-01, 4.3883e-01, 1.7798e-01],
         [9.0903e-04, 2.9150e-01, 8.8188e-01]

In [171]:
x_permuted

tensor([[[8.6940e-01, 4.2940e-01, 2.6658e-01,  ..., 8.8455e-01,
          4.5545e-02, 5.6972e-01],
         [3.3968e-01, 3.4206e-01, 6.5762e-01,  ..., 6.7008e-01,
          4.8892e-01, 5.3223e-01],
         [1.8443e-01, 3.5680e-01, 2.3124e-02,  ..., 5.4622e-01,
          8.4301e-01, 4.9887e-01],
         ...,
         [7.5457e-01, 9.0903e-04, 3.5989e-01,  ..., 2.5104e-01,
          2.5154e-01, 1.7896e-01],
         [9.8712e-01, 1.5513e-01, 7.4419e-01,  ..., 5.5916e-01,
          6.1312e-01, 3.4504e-01],
         [9.6185e-01, 6.3930e-01, 1.3687e-01,  ..., 7.0843e-01,
          8.6134e-01, 1.1667e-01]],

        [[5.6772e-01, 8.8544e-01, 6.2745e-01,  ..., 3.8850e-01,
          4.2129e-01, 2.0877e-01],
         [9.5650e-01, 1.7213e-02, 9.8131e-01,  ..., 6.1587e-02,
          2.9742e-01, 8.5103e-01],
         [8.5328e-01, 1.7045e-01, 6.3169e-01,  ..., 6.2962e-01,
          2.0853e-01, 9.3264e-02],
         ...,
         [4.3883e-01, 2.9150e-01, 1.9892e-01,  ..., 6.5680e-01,
          5.895

### Indexing (selecting data from tensors)

In [172]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x.shape

torch.Size([1, 3, 3])

In [173]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


You can also use `:` to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [174]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [175]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [176]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [177]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :]

tensor([1, 2, 3])

In [178]:
x[0, 0, 2]

tensor(3)

### PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

    torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
    torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [179]:
import numpy as np

In [180]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))



    Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

    However, many PyTorch calculations default to using float32.

    So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).


In [181]:
tensor = tensor.type(torch.float32)
tensor.dtype

torch.float32

In [182]:
# Because we reassigned the tensor above, if you change the tensor, the darray stays the same
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [183]:
# from tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [184]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [186]:
tensor = torch.arange(10, 100, 10)
print(tensor)

print(f"index of max value: {tensor.argmax()}")
print(f'index of min value: {tensor.argmin()}')

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
index of max value: 8
index of min value: 0


### Reproducibility (trying to take the random out of random)

What if we want to create two tensors with same values randomely?

As in, the tensors would still contain random values but they would be of the same flavour.

That's where `torch.manual_seed(seed)` comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

Let's try it out by creating some more flavoured random tensors.

In [213]:
RANDOM_SEED = 2005
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand((3, 4))

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand((3, 4))
print(random_tensor_C)
print(random_tensor_D)
random_tensor_D == random_tensor_C


tensor([[0.2249, 0.7745, 0.5017, 0.3579],
        [0.6479, 0.1607, 0.3716, 0.3174],
        [0.2452, 0.6733, 0.5015, 0.1196]])
tensor([[0.2249, 0.7745, 0.5017, 0.3579],
        [0.6479, 0.1607, 0.3716, 0.3174],
        [0.2452, 0.6733, 0.5015, 0.1196]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [214]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'